# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20160120_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='elapsed_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elapsed time (h)'),
        ),
    ]
