# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-26 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20160121_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 26, 18, 26, 32, 458580, tzinfo=utc), verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_day',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 26, 18, 26, 42, 400439, tzinfo=utc), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
    ]
