# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_auto_20160126_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
