# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20160126_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_day',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
