# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_comment_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='scheduling.Comment'),
        ),
    ]
