# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_auto_20160129_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduling.Equipment'),
            preserve_default=False,
        ),
    ]
