# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_ticket_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
    ]
