# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_auto_20160216_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='service_record',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='service_record',
        ),
        migrations.AddField(
            model_name='service',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scheduling.Component'),
        ),
        migrations.AddField(
            model_name='service',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scheduling.Equipment'),
            preserve_default=False,
        ),
    ]
