# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_auto_20160216_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='successs',
            field=models.BooleanField(default=True, verbose_name='Success'),
        ),
    ]
