# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-22 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_service_successs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='successs',
            new_name='success',
        ),
    ]
